### ISSUE TITLE
401 Error despite entered user data Server 0.9.16.6 forced https

### ISSUE THREAD

**Issue by MReptile** [ukdtom/Plex-FindUnmatched.bundle#100]
Could you please make your script work with this newest release with https?
Furthermore I only have read access to the movie folders. (Is that causing a problem?)
In addition this is running as a docker container. This should not cause any problems.

But could you look into it? I would really appreciate your help.

Kind regards

Reptile

**Comment by ukdtom** [comment]
It does work!

401 means access denied, aka.......

You didn't enter your plex.tv credentials, or didn't check the "Authenticate @ plex.tv (Use if running in Home mode)" checkbox.

And if above, and after making those changes, restart the PMS

Another possibility could also be, that your PMS has lost contact with plex.tv, so make sure that it can be reached from the outside

And regardless, please respond back, and if non of above helped, I'll need logs in indbug mode

/T

**Comment by MReptile** [comment]
First of all I would like to apologize. I didn't mean to be rude at all.
Your software is indeed working perfectly. It was a docker problem. It didn't correctly restart the plex process.

Your software perfectly shows which files are not present in the plex database.
Is it possible for you to add the following feature? Because I have the following problem:

When Plex maches a movie. You can click on the movie to see the details.
In this screen you have on the left side three dots. When clicking on this three dots you see "Unmatch" and "Fix incorrect match". If so the title has been matched against the online db.

Sometimes Plex can't correctly identify a title and uses local media assets. In this case when clicking on the three dots you see "match" as an option.
I would like to be able to generate a list with all the movies that still need to be matched, despite the database entry. Because if not matched it shows some weird information like "Title C.3".

I am so sorry. I am not a native. I hope i could explain my problem.
I would happily donate, if you could help me to solve my problem
I need this, because my Plex is fully automated and I have thousands of dvds. So I cannot click on all of them...

Thank you for your help in advance.

Yours sincerely 

Reptile

**Comment by ukdtom** [comment]
Didn't in any way take it negative, so no problem here ;-)

And wow.....never ever seen that, but guess that's due to having perfectly matched files myself ;-)

What I need you to do, is sending me the XML of such a media, and if I can spot something in that, I might be able to not add it to this little program/util, but instead to Plex2CSV, since that already grabs all the info out from a media, where Find-Unmatched doesn't.

You can send me the XML in a PM on the forums

**Comment by MReptile** [comment]
on which forum.
There seems to be no difference in the XML Files. Both contain IMDB_ID and TMDB ID.
I will send them to you of course as soon as I know in which forum.
Is it possible that the value to know, wether it is matched or not is stored in the Plex Database?
Is it possilble for you to check that. I mean somehow the Plex Server has to keep Track of Matched and unmatched media.

My XMLs are created by a programm called "MediaCenterMaster" before moved to and indexed by Plex.
So I don't think that the difference can be found there.

**Comment by ukdtom** [comment]
Sorry....

The Plex forums.

My user ID up there is dane22

**Comment by XtraLarge** [comment]
Hi,
I've also an error 401, but I can bypass it by delete the PIN code.

**Comment by ukdtom** [comment]
@XtraLarge Please start a new issue on this, and more details here, like OS, logs as well as info about what PIN you are talking about
