### ISSUE TITLE
Can't find any content

### ISSUE THREAD

**Issue by starcaster99** [ukdtom/Plex-FindUnmatched.bundle#101]
I am missing a few movies, I should have 1316 and Plex shows 1311 with no duplicates on the Plex Movie page.

I can't get your plugin to run.  (It won't work on any media type, not just movies)

Internal Error Detected. Please check the logs FindUnmatched V1.0.0.9

[com.plexapp.plugins.findUnmatch.log.1.zip](https://github.com/ukdtom/Plex-FindUnmatched.bundle/files/349590/com.plexapp.plugins.findUnmatch.log.1.zip)

Please advise.

**Comment by ukdtom** [comment]
You have according to the log put your medias in the root of drive e:
That is not recommended, since most OS like Windows puts in system folders, that can't be accessed.

`File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-a17e99e\Framework.bundle\Contents\Resources\Versions\2\Python\subsystem\ospathfix.py", line 105, in os_listdir
    return os._listdir(longpathify(uni(path)))
WindowsError: [Error 5] Access is denied: u'\\\\?\\E:\\$RECYCLE.BIN\\S-1-5-21-1613838194-3394590850-2946036872-1001\\*.*'`

As such, you'll need to exclude the directory named RECYCLE.BIN in the settings of Find.Unmatched.

Let me know the outcome

**Comment by starcaster99** [comment]
I looked at the settings and I don't see anywhere to exclude any
directories.

*Not sent from a*ny Ap*p*le* Dev*ic*e.*

**Comment by ukdtom** [comment]
![find-unmatched](https://cloud.githubusercontent.com/assets/4699449/16617106/0296e344-4382-11e6-9567-c78c5b811e6c.png)

**Comment by starcaster99** [comment]
I found it right before you send your message.
I put in:

 .@__thumb, .AppleDouble, lost+found, E:\$RECYCLE.BIN

No error now, it just says that filesystem is empty

*Not sent from a*ny Ap*p*le* Dev*ic*e.*

**Comment by starcaster99** [comment]
OK, so I made a Movie directory on E: and moved all the movies into it.  I
am still getting the same error.

*Not sent from a*ny Ap*p*le* Dev*ic*e.*

**Comment by ukdtom** [comment]
And did you also update the path in your PMS library?

**Comment by starcaster99** [comment]
It's mapped to E:\Movies now.  Plex just had a heart attack and is
reloading all of the movies again :-(
But, your program is now working.  I won't know if there is any further
issues for a while.

*Not sent from a*ny Ap*p*le* Dev*ic*e.*

**Comment by ukdtom** [comment]
Next time:

https://support.plex.tv/hc/en-us/articles/201154537-Move-Media-Content-to-a-New-Location

And closing this for now.

Feel free to open a new issue if needed

/T

**Comment by starcaster99** [comment]
OK, here is what I found.  The program says no movies are missing.  But, I
still have the problem that my movie folder physically shows 1316 movies
and Plex shows 1311.  I am short 5.  For a brief moment, Plex did show
1316, but dropped back down to 1311.

*Not sent from a*ny Ap*p*le* Dev*ic*e.*

**Comment by ukdtom** [comment]
Try this:

https://support.plex.tv/hc/en-us/articles/202393718-How-do-I-find-duplicate-or-merged-content-

**Comment by starcaster99** [comment]
Unfortunately, they are not duplicates.  That was the first thing I checked.
Sometimes when you add multiple files, the plex xml files get messed up, so
two or more unrelated movies get joined together in the database and only
one is displayed on the server.  The only way I know how to fix it is to
move the missing movie files out of the movie directory and put them back
one at a time.  It would be nice if you could scan the entries to find
which xml files have more than one movie attached.  I know nothing about
python script.  I don't know how it compares the physical files to what is
in the database.  It did not catch the missing movies, and the movies do
play and all have an mp4 extension.

*Not sent from a*ny Ap*p*le* Dev*ic*e.*

**Comment by ukdtom** [comment]
If you didn't have any duplicates, and Find-Unmatched also didn't detect any, then all I can think of, is that some of your medias are in an invalid format, not supported by PMS.

You might then try Find-Missing plugin

**Comment by starcaster99** [comment]
Well, when I take them out of the directory, rescan the directory, put them
back in, and rescan the directory again, they show up.  It's a problem with
Plex intermittently putting two unrelated movies in the same xlm file as I
said.  When you remove the movie in question, the bad xlm file goes away
and new files are created upon reinput.  That is why I said that there
needs to be something that checks xlm files for multiple entries.  I am not
the only one who has had this problem, it has been cited many times by
others.

*Not sent from a*ny Ap*p*le* Dev*ic*e.*

**Comment by ukdtom** [comment]
But if they where in the same xml, then should show as such, when the duplicate filter was enabled in WebAdmin!

**Comment by starcaster99** [comment]
The file is treating them as one movie, with the first one listed as the
one that actually shows and plays.  The second title is on a subsequent
line is not always picked up in PMS.  Once in a while it is, and that makes
it easy to take care of.  Otherwise, your stuck because the PMS directory
structure makes it very hard to find the errant xlm file.

*Not sent from a*ny Ap*p*le* Dev*ic*e.*

**Comment by ukdtom** [comment]
If so, then it's a problem with your database contents, and explains why it didn't get detected by Find-Unmatched.

Got a sample of the bad XML?

**Comment by starcaster99** [comment]
If I find one, I will send it your way.  As I said, they are almost
impossible to find due to the directory structure in PMS.
But yes, it is a problem with the database contents.  It is not restricted
to movies, it can happen to any content and only occurs when you do a
massive scan of new content.  One, or a few at a time, is never a problem.

*Not sent from a*ny Ap*p*le* Dev*ic*e.*
