### ISSUE TITLE
FEATURE REQUEST: add schedule

### ISSUE THREAD

**Issue by kossboss** [ukdtom/Plex-FindUnmatched.bundle#83]
add schedule to run this system.

people consistently add new things to their plex, it would be nice to have the unmatched results be sitting in some folder for you, ready to be analyzed with the latest results.

**Comment by ukdtom** [comment]
Not possible with the Plex Framework API, without having the bundle run always in the background, and since the use-case is limited, it's a no go

**Comment by kossboss** [comment]
If there is a will there is always a way. For one you don't have to rely
completely y of plex. Think outside the box. For one you said there is a
URL one can go to immediately initiate it. So one can use cron with Linux,
or windows scheduler, or whatever with macs to start that url at whatever
time. You could include a tipbox or extra Info label for each section
selection box where u provide that link...

**Comment by ukdtom** [comment]
Sadly not as easy as you put it, since a plugin live under the hood of the website, and if authentication is enabled, so to launch an url against it, things get's more complicated. Due to that, It's a Won't fix, based on the work I have to do, combined with the IMHO limited  use case.
