### ISSUE TITLE
False positive unmatch

### ISSUE THREAD

**Issue by Jellyfrog** [ukdtom/Plex-FindUnmatched.bundle#90]
FindUnmatched seems to convert encoded names which causes it to give an false positive match.
So I'm getting a "unmatched file" but Plex is matching it correctly

Filename on disk: `serie.s01e01.foo%27bar.mkv`
Plex: `serie.s01e01.foo%27bar.mkv`
FindUnmatched: `serie.s01e01.foo'bar.mkv`

**Comment by ukdtom** [comment]
That will not be fixed, due to the fact, that it then will break about 100% other stuff.

%27 is the utf-8 character for the ' sign

And....Please give real names next time, in order for me to at least have a chance to validate, if a report is for fix or decline
