### ISSUE TITLE
shows local movie extras -short and -featurette as unmatched

### ISSUE THREAD

**Issue by OttoKerner** [ukdtom/Plex-FindUnmatched.bundle#93]
v 1.0.0.8 shows the newly introduced (PMS 0.9.14) local movie extras -short and -featurette as unmatched, even though they are listed perfectly among the other extras
![findunmatched1](https://cloud.githubusercontent.com/assets/10280992/11815413/e7093252-a34b-11e5-9900-2e2852d55fae.png)

![findunmatched2](https://cloud.githubusercontent.com/assets/10280992/11815417/eb62b3c8-a34b-11e5-9508-b5e628aa7c86.png)

**Comment by ukdtom** [comment]
Fixed in V1.0.0.9
