### ISSUE TITLE
Switch view from posters to List

### ISSUE THREAD

**Issue by daeks** [ukdtom/Plex-FindUnmatched.bundle#94]
Is it possible to switch the view from poster to list by default?

**Comment by ukdtom** [comment]
Sadly not.
Been trying to make it work a couple of times, but guess I'm not bright enough :-(

**Comment by daeks** [comment]
too bad :( I also checked the code from another plugin, but didnt find any difference between yours and that (https://github.com/MaZZly/BringThePopcorn.bundle) which seems to have listing enabled

**Comment by ukdtom** [comment]
Try, been banging my head here :-(

And closing this, since I'll soon start working on an alternative route anyway
