### ISSUE TITLE
Internal Error Detected

### ISSUE THREAD

**Issue by pdupreez** [ukdtom/Plex-FindUnmatched.bundle#99]
Immediately when running a scan on either Movies or TV section this error message pops up. 

Running version 1.0.0.9 on a QNAP TVS-EC1080, with firmware 4.2.0 build 20160311, and Plex Server version 2.6.1, with Plex Pass

[com.plexapp.plugins.findUnmatch.zip](https://github.com/ukdtom/Plex-FindUnmatched.bundle/files/264508/com.plexapp.plugins.findUnmatch.zip)

**Comment by ukdtom** [comment]
Log says:

`HTTPError: HTTP Error 401: Unauthorized`

Make sure that plex.tv credentials are entered, and plex.tv authentication is enabled in FindUnmatched settings.

If already so, then try a PMS restart

/T

**Comment by ukdtom** [comment]
Closed due to lack of response
